name: CI

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Nim
        uses: jiro4989/setup-nim-action@5bbc93d889ba575ed95cde254faa197193690456
      - name: Install dependencies
        run: nimble install -d -y
      - name: Run tests
        run: nimble test -y
      - name: Check formatting
        run: |
          find . -name '*.nim' -exec nimpretty --indent:2 {} \;
          git diff --exit-code
